name: push-images

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/push-images.yml"
  push:
    branches:
      - develop
      - fix/move-docker-images

jobs:
  move-images:
    runs-on: [self-hosted, common]

    steps:
      - name: Login to Registry nexus
        uses: docker/login-action@v2
        with:
          registry: docker.registry.apps.centreon.com
          username: ${{ secrets.NEXUS_RPMS_REPOSITORY_USERNAME }}
          password: ${{ secrets.NEXUS_RPMS_REPOSITORY_PASSWORD }}

      - name: Login to Registry arti
        uses: docker/login-action@v2
        with:
          registry: registry-docker.centreon.com
          username: ${{ secrets.ARTI_USER }}
          password: ${{ secrets.ARTI_PASSWD }}

      - run: |
          docker pull  docker.registry.apps.centreon.com/mon-mediawiki-22.10:latest
          docker tag  docker.registry.apps.centreon.com/mon-mediawiki-22.10:latest registry-docker.centreon.com/docker-global/mon-mediawiki-22.10:latest
          docker push  registry-docker.centreon.com/docker-global/mon-mediawiki-22.10:latest

          docker pull  docker.registry.apps.centreon.com/mon-mediawiki-22.04:latest
          docker tag  docker.registry.apps.centreon.com/mon-mediawiki-22.04:latest registry-docker.centreon.com/docker-global/mon-mediawiki-22.04:latest
          docker push  registry-docker.centreon.com/docker-global/mon-mediawiki-22.04:latest

          docker pull  docker.registry.apps.centreon.com/mon-mediawiki-21.10:latest
          docker tag  docker.registry.apps.centreon.com/mon-mediawiki-21.10:latest registry-docker.centreon.com/docker-global/mon-mediawiki-21.10:latest
          docker push  registry-docker.centreon.com/docker-global/mon-mediawiki-21.10:latest

          docker pull  docker.registry.apps.centreon.com/mon-mediawiki-21.04:latest
          docker tag  docker.registry.apps.centreon.com/mon-mediawiki-21.04:latest registry-docker.centreon.com/docker-global/mon-mediawiki-21.04:latest
          docker push  registry-docker.centreon.com/docker-global/mon-mediawiki-21.04:latest

        shell: bash
